### PR TITLE
Buff to Enclave

### PR DESCRIPTION
**Pull request by Waklaidan**
## About The Pull Request
Added Enclave heavy infantry with gatling laser

## Why It's Good For The Game

the enclave has been buffed and can now properly counter other factions

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added heavy infantry for enclave
balance: Buffed enclave
/:cl:

### CODE REVIEW

**Comment by Waklaidan** [comment]
made by @Egorium, but he has problems with github, so I did it for him

**Comment by BadAtThisGame302** [comment]
Enclave doesn't need a buff, already have more than enough roles and having two APA instead of one is a bad idea

**Comment by Egorium** [comment]
> Enclave doesn't need a buff, already have more than enough roles and having two APA instead of one is a bad idea

Remove all PA from BoS then, except Head Paladin armor

**Comment by BadAtThisGame302** [comment]
> > Enclave doesn't need a buff, already have more than enough roles and having two APA instead of one is a bad idea
> 
> Remove all PA from BoS then, except Head Paladin armor

The Enclave are remnants of remnants, it's unlikely they'd have multiple sets of APA

**Comment by Egorium** [comment]
> > > Enclave doesn't need a buff, already have more than enough roles and having two APA instead of one is a bad idea
> > 
> > 
> > Remove all PA from BoS then, except Head Paladin armor
> 
> The Enclave are remnants of remnants, it's unlikely they'd have multiple sets of APA

Before they became remnants, almost every member of the Enclave had power armor, then they became remnants and all the armor disappeared somewhere

**Comment by Egorium** [comment]
I think that there is nothing wrong with adding a heavy infantry at least for a while to see if he breaks the balance or not. You can always remove it from the code

**Pull request merged**
